namespace backend.Business.Models;

/// <summary>
/// Represents a ticket booking transaction.
/// Links a user to a specific seat on a train with payment and status information.
/// All DateTime properties are stored in UTC timezone in the database.
/// </summary>
public class Booking
{
	public int BookingId { get; set; }
	public int UserId { get; set; }
	public int TrainId { get; set; }
	public int SeatId { get; set; }
	public string BookingStatus { get; set; } = string.Empty;

	/// <summary>
	/// Booking creation timestamp in UTC timezone.
	/// Auto-generated by database using GETUTCDATE().
	/// </summary>
	public DateTime BookingDate { get; set; }

	public decimal TotalAmount { get; set; }
	public string PaymentStatus { get; set; } = string.Empty;

	/// <summary>
	/// Cancellation timestamp in UTC timezone (null if not cancelled).
	/// Frontend should convert to local time for display.
	/// </summary>
	public DateTime? CancelledAt { get; set; }
}