namespace backend.Business.Models;

/// <summary>
/// Represents enriched booking history information with complete train and seat details.
/// Used for displaying booking history in client applications.
/// This is a read-only DTO combining data from Booking, Train, and Seat tables.
/// All DateTime properties are in UTC timezone (converted to local time by frontend).
/// </summary>
public class BookingHistory
{
	/// <summary>
	/// Unique identifier for the booking.
	/// </summary>
	public int BookingId { get; set; }

	/// <summary>
	/// Unique identifier for the train.
	/// </summary>
	public int TrainId { get; set; }

	/// <summary>
	/// Train number (e.g., "SE1", "TN2").
	/// </summary>
	public string TrainNumber { get; set; } = string.Empty;

	/// <summary>
	/// Train name (e.g., "Thống Nhất", "Sài Gòn").
	/// </summary>
	public string TrainName { get; set; } = string.Empty;

	/// <summary>
	/// Departure station name.
	/// </summary>
	public string DepartureStation { get; set; } = string.Empty;

	/// <summary>
	/// Arrival station name.
	/// </summary>
	public string ArrivalStation { get; set; } = string.Empty;

	/// <summary>
	/// Train departure time in UTC timezone.
	/// Frontend should convert to local time for display.
	/// </summary>
	public DateTime DepartureTime { get; set; }

	/// <summary>
	/// List of seat numbers for this booking (e.g., ["A1", "A2"]).
	/// Currently one seat per booking, but supports multiple for future enhancement.
	/// </summary>
	public List<string> SeatNumbers { get; set; } = new List<string>();

	/// <summary>
	/// Booking creation timestamp in UTC timezone.
	/// Auto-generated by database using GETUTCDATE().
	/// </summary>
	public DateTime BookingDate { get; set; }

	/// <summary>
	/// Booking status: "Pending", "Confirmed", "Cancelled".
	/// </summary>
	public string BookingStatus { get; set; } = string.Empty;

	/// <summary>
	/// Payment status: "Pending", "Paid", "Refunded".
	/// </summary>
	public string PaymentStatus { get; set; } = string.Empty;

	/// <summary>
	/// Total amount for this booking.
	/// </summary>
	public decimal TotalAmount { get; set; }

	/// <summary>
	/// Cancellation timestamp in UTC timezone (null if not cancelled).
	/// Frontend should convert to local time for display.
	/// </summary>
	public DateTime? CancelledAt { get; set; }
}