namespace backend.Business.Models;

/// <summary>
/// Represents a train schedule with route, timing, and seat information.
/// Used for managing train operations and ticket availability.
/// All DateTime properties are stored in UTC timezone in the database.
/// </summary>
public class Train
{
	public int TrainId { get; set; }
	public string TrainNumber { get; set; } = string.Empty;
	public string TrainName { get; set; } = string.Empty;
	public string DepartureStation { get; set; } = string.Empty;
	public string ArrivalStation { get; set; } = string.Empty;

	/// <summary>
	/// Departure time in UTC timezone.
	/// Frontend should convert to local time for display.
	/// </summary>
	public DateTime DepartureTime { get; set; }

	/// <summary>
	/// Arrival time in UTC timezone.
	/// Frontend should convert to local time for display.
	/// </summary>
	public DateTime ArrivalTime { get; set; }

	public int TotalSeats { get; set; }
	public decimal TicketPrice { get; set; }
	public string Status { get; set; } = string.Empty;

	/// <summary>
	/// Creation timestamp in UTC timezone.
	/// Auto-generated by database using GETUTCDATE().
	/// </summary>
	public DateTime CreatedAt { get; set; }
}